config/routes.rb
Scalpel::Application.routes.draw do
  root :to => 'home#index'
  
resources :users, :except => [:edit] do
  collection do
    get 'edit'
  end
end
post '/shows' => 'websites#shows'
get '/shows' => 'websites#shows'
resources :home, :websites, :presets

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete 'login' => 'session#destroy'
end

app/models/preset.rb
# == Schema Information
#
# Table name: presets
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Preset < ActiveRecord::Base
  attr_accessible :name
  belongs_to :user, :inverse_of => :presets
  has_and_belongs_to_many :websites
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  user_id         :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :name, :email, :password, :password_confirmation
  has_many :presets, :inverse_of => :user
  validates :name, :uniqueness => true, :length => { :minimum => 1 }
end 

app/models/website.rb
# == Schema Information
#
# Table name: websites
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  image_url              :string(255)
#  url                    :string(255)
#  nokogiri_selector      :string(255)
#  nokogiri_link_selector :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Website < ActiveRecord::Base
  attr_accessible :name, :url, :image_url, :nokogiri_selector, :nokogiri_link_selector
  has_and_belongs_to_many :presets
  require 'open-uri'

  def image_scrape
    doc = Nokogiri::HTML(open(self.url)) #this opens the url attr within its one instance and grabs all the html data and allows nokogiri to parse it.
    images = doc.css(self.nokogiri_selector)
    image_urls = images.map {|i| i.get_attribute('src')}
    image_urls #this returns the result of the function which is an array of src of the images(the location url)
  end

  def link_scrape
    doc = Nokogiri::HTML(open(self.url))
    links = doc.css(self.nokogiri_link_selector)
    link_urls = links.map {|l| l.get_attribute('href')}
    link_urls
  end
end
# {:image => i.get_attribute('src'), :link => i.get_attribute('href')}

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery
  before_filter :authentication

  private
  def authentication
    @auth = User.find(session[:user_id]) if session[:user_id].present?
  end

  def check_if_logged_in
    redirect_to(root_path) if @auth.nil?
  end

  def check_if_admin
    redirect_to(root_path) if @auth.nil? || !@auth.is_admin
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
    redirect_to websites_path if @auth.present?
  end
end

app/controllers/presets_controller.rb
class PresetsController < ApplicationController

  # before_filter :check_if_user, :only => [:new, :create]
  # before_filter :check_if_specific_user, :only => [:show]

  def show
    @preset = Preset.find(params[:id])
  end
  def new
    @preset = Preset.new
  end
  def create
    @preset = Preset.new(params[:preset])
    if @preset.save
      @auth.presets << @preset
      redirect_to(root_path)
    else
      render :new
    end
  end
  def index
      @presets = Preset.order(:name)
  end

  private
  def check_if_specific_user
    redirect_to(root_path) if @auth.nil? || @auth.preset_ids.exclude?(params[:id].to_i)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new

  end
  def create
    user = User.where(:email => params[:email]).first
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      @websites = Website.all
      redirect_to websites_path
    else
      flash[:notice] = 'Incorrect login, try again.'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to(root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_filter :check_if_logged_in, :except => [:new, :create]
  # before_filter :check_if_admin, :only => [:index, :destroy]

  def index
    @users = User.all
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to(root_path)
    else
      render :new
    end
  end
 private
  def check_if_logged_in
    redirect_to(root_path) if @auth.nil?
  end
end

app/controllers/websites_controller.rb
require 'open-uri'
# before_filter :check_if_admin, :except => [:show, :index]

class WebsitesController < ApplicationController
  def shows
    @websites = Website.find(params[:ids])
    @images = @websites.map{|i| i.image_scrape}.flatten
    @links = @websites.map{|i| i.link_scrape}.flatten
  end

  def index
    @websites = Website.order(:name)
  end

  def new
    @website = Website.new
  end
  def create
    @website = Website.new(params[:website])
    if @website.save
      redirect_to(websites_path)
    else
      render :new
    end
  end
  def edit
    @website = Website.find(params[:id])
    render :new
  end
  def update
    @website = Website.find(params[:id])
    if @website.update_attributes(params[:website])
      redirect_to(websites_path)
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def intellinav
    if @auth.present?
      link_to("Log Out #{@auth.name.titleize}", login_path, :method => :delete)

    else
      link_to('login', login_path, :id => 'logbutton', :remote => true)
    end
  end
end

app/views/home/index.html.haml
.row
  %br
  %br
  %br
  %br
  %br
  %br
  %br
  %br
  %br
  %br
  .large-12.columns
    #indexlogbox
  .large-12.columns
    .index 
      = link_to('login', login_path, :id => 'logbutton', :remote => true)
      %h1 scalpel
      = link_to(' new user ', new_user_path, :id => 'registerbutton', :remote => true)
  .large-12.columns
    %br
    #indexregisterbox

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scalpel</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
  </div>
</body>
</html>

app/views/presets/index.html.haml
-@presets.each do |f|
	%p=f.name

app/views/presets/new.html.haml
%h3= @preset.name

app/views/users/index.html.haml
#users

  %table
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email

app/views/websites/index.html.haml
#container
  = render :partial => 'layouts/nav' 
  .row
    .large-12.columns
      %br
      #new_website_form


    .large-12.columns
      %br
      #website_button
        =button_tag 'Scrape', :id => 'scrape_button'
        =button_tag 'Add to Presets', :id => 'preset_button'
        =link_to('New Website', new_website_path, :remote => 'true')
        %br

    .large-12.columns
      %br
      %br
      - @websites.each do |website|
        .website_box{ data: { id: website.id } }
          %br
          %td= link_to(website.name.titleize, website.url, :target => '_blank')
          %br
          %br
          %td= link_to image_tag(website.image_url), website.url, :target => '_blank'
          %br
          %br